<?php
$banco = $this->banco;
$agencia = $this->agencia;

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Banco' => $this->url('banco'),
    'Agencia' => $this->url('agencia', ['ban_id' => $banco->getId()]),
    'Edit' => '#',
]);

$form = $this->form;
$form->prepare();


$form->get('nome')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Nome',
    'value' => $agencia->getNome(),
]);

$form->get('endereco')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Endereço',
    'value' => $agencia->getEndereco(),
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-success']);
?>
<h1>CADASTRO DE AGENCIA</h1>
<h2><?= $banco->getDescricao() ?></h2>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('nome')); ?>
            <?= $this->formElement($form->get('nome')); ?>
            <?= $this->formElementErrors($form->get('nome')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('endereco')); ?>
            <?= $this->formElement($form->get('endereco')); ?>
            <?= $this->formElementErrors($form->get('endereco')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>    
</div>