<?php

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home'),
    'Login' => $this->url('login'),
    'Index' => '#',
]);

$form = $this->form;
$form->prepare();
?> 
<h1> Login </h1>
<div class="row">
   <div class="col-md-6">
      <?= $this->form()->openTag($form); ?>
   </div>
   
   <div class="form-group"> 
      <?= $this->formLabel($form->get('login'));?>
      <?= $this->formElement($form->get('login'));?>
      <?= $this->formElementErrors($form->get('login'));?>
   </div>
   
   <div class="form-group"> 
      <?= $this->formLabel($form->get('password'));?>
      <?= $this->formElement($form->get('password'));?>
      <?= $this->formElementErrors($form->get('password'));?>
   </div>
   
   <div class="form-group"> 
      <?= $this->formElement($form->get('submit'));?>
      <?= $this->formElementErrors($form->get('submit'));?>
   </div>
</div>
